<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>0db41932-87ee-46b8-877c-33b3140d9013</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
    </ItemGroup>

</Project>
