<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>083f0e57-6ba2-4fae-9322-ad08a547f717</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
    </ItemGroup>

</Project>
